"use client";
import { useCallback, useEffect, useState } from "react";
import { getOperationsSettings, listOperationalAlerts, listOperationalTrips, OperationsSettings, resolveDriverNoShow, resolveOperationalAlert, saveOperationsSettings } from "./lib/operationsApi";

const defaults: OperationsSettings = { reminderEveryMinutes: 5, maxReminders: 6, escalateAfterReminders: 2, locationStaleMinutes: 10, maxActiveTripsPerDriver: 2, maxActiveTripsPerVehicle: 1, driverNoShowReportAfterMinutes: 15, maxReportedDelayMinutes: 240, driverTurnaroundMinutes: 480 };
const statusLabel: Record<string, string> = { PUBLISHED: "Publicado", FULL: "Completo", MEETING: "En encuentro", IN_PROGRESS: "En recorrido", COMPLETED: "Finalizado" };
const settingFields = [
  ["reminderEveryMinutes", "Cada cuántos minutos", "Intervalo entre recordatorios mientras una tarea continúe pendiente."],
  ["maxReminders", "Máximo de recordatorios", "Cantidad máxima de veces que se repetirá una alerta."],
  ["escalateAfterReminders", "Escalar a soporte después de", "Número de recordatorios tras el cual la alerta sube de prioridad."],
  ["locationStaleMinutes", "GPS sin actualizar (min)", "Minutos sin nueva ubicación antes de advertir a soporte."],
  ["maxActiveTripsPerDriver", "Máximo activo por conductor", "Publicaciones activas simultáneas permitidas para un conductor."],
  ["maxActiveTripsPerVehicle", "Máximo activo por vehículo", "Publicaciones activas simultáneas permitidas para el mismo vehículo."],
  ["driverTurnaroundMinutes", "Separación mínima entre viajes (min)", "Tiempo obligatorio entre el final estimado de un viaje y el inicio del siguiente para el conductor o vehículo."],
  ["driverNoShowReportAfterMinutes", "Espera para reportar conductor ausente (min)", "Tiempo que debe pasar antes de habilitar el reporte de no presentación."],
  ["maxReportedDelayMinutes", "Máximo retraso reportable (min)", "Límite de retraso que el conductor puede informar desde la app."],
] as const;

export default function OperationsPage() {
  const [trips, setTrips] = useState<any[]>([]), [alerts, setAlerts] = useState<any[]>([]), [settings, setSettings] = useState(defaults);
  const [message, setMessage] = useState(""), [busy, setBusy] = useState("");
  const load = useCallback(async () => { try { const [t, a, s] = await Promise.all([listOperationalTrips(), listOperationalAlerts(), getOperationsSettings()]); setTrips(t); setAlerts(a); setSettings({ ...defaults, ...s }); } catch (e: any) { setMessage(e.message); } }, []);
  useEffect(() => { void load(); const id = window.setInterval(() => void load(), 30000); return () => window.clearInterval(id); }, [load]);
  async function resolve(id: string) { try { setBusy(id); await resolveOperationalAlert(id); await load(); } catch (e: any) { setMessage(e.message); } finally { setBusy(""); } }
  async function noShow(alert: any, decision: "CONFIRM" | "DISMISS") { const notes = window.prompt(decision === "CONFIRM" ? "Conclusión del caso y detalle para el usuario:" : "Motivo para descartar el reporte:") || ""; if (!notes || !alert.tripId) return; try { setBusy(alert.id); await resolveDriverNoShow(alert.tripId, decision, notes); await resolveOperationalAlert(alert.id); await load(); } catch (e: any) { setMessage(e.message); } finally { setBusy(""); } }
  async function save() { try { setBusy("settings"); await saveOperationsSettings(settings); setMessage("Configuración operativa guardada."); } catch (e: any) { setMessage(e.message); } finally { setBusy(""); } }
  const openAlerts = alerts.filter((a) => !a.resolvedAt);
  return <main className="space-y-6 p-6"><header><p className="text-sm font-bold text-emerald-600">Ruta KroniX</p><h1 className="text-3xl font-black">Centro de operación</h1><p className="mt-2 text-sm text-slate-500">Seguimiento de viajes, alertas y tareas que requieren atención.</p></header>
    {message ? <div className="rounded-2xl bg-blue-50 p-4 text-sm text-blue-800">{message}</div> : null}
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{trips.map((trip) => <article key={trip.id} className="rounded-3xl border bg-white p-5"><div className="flex justify-between gap-3"><strong>{trip.route.originCity.name} → {trip.route.destinationCity.name}</strong><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700">{statusLabel[trip.status] || trip.status}</span></div><p className="mt-2 text-sm text-slate-500">{new Date(trip.departureAt).toLocaleString("es-CO")}</p><p className="mt-3 font-semibold">{trip.driver.name}</p><p className="text-sm text-slate-500">{trip.driver.phone} · {trip.bookings.length} reservas</p>{trip.lastLat != null ? <a className="mt-4 inline-block rounded-xl bg-slate-950 px-3 py-2 text-sm font-bold text-white" target="_blank" rel="noreferrer" href={`https://www.google.com/maps?q=${trip.lastLat},${trip.lastLng}`}>Ver última ubicación</a> : <p className="mt-4 text-xs text-amber-700">Sin ubicación reportada</p>}</article>)}</section>
    <section className="rounded-3xl border bg-white p-6"><h2 className="text-xl font-black">Alertas pendientes <span className="text-red-600">({openAlerts.length})</span></h2><div className="mt-4 space-y-3">{openAlerts.length === 0 ? <p className="text-slate-500">La operación está al día.</p> : openAlerts.map((alert) => <article key={alert.id} className="flex flex-col gap-3 rounded-2xl bg-slate-50 p-4 lg:flex-row lg:items-center"><div className="flex-1"><div className="flex gap-2"><strong>{alert.title}</strong><span className="text-xs font-bold text-red-600">{alert.priority}</span></div><p className="text-sm text-slate-600">{alert.body}</p><p className="mt-1 text-xs text-slate-400">{new Date(alert.createdAt).toLocaleString("es-CO")} · {alert.reminderCount || 0} recordatorios</p></div>{alert.type === "DRIVER_NO_SHOW_REPORTED" ? <div className="flex gap-2"><button disabled={busy === alert.id} onClick={() => void noShow(alert, "CONFIRM")} className="rounded-xl bg-red-600 px-4 py-2 font-bold text-white">Confirmar ausencia</button><button disabled={busy === alert.id} onClick={() => void noShow(alert, "DISMISS")} className="rounded-xl bg-slate-600 px-4 py-2 font-bold text-white">Descartar</button></div> : <button disabled={busy === alert.id} onClick={() => void resolve(alert.id)} className="rounded-xl bg-emerald-600 px-4 py-2 font-bold text-white">Marcar atendida</button>}</article>)}</div></section>
    <section className="rounded-3xl border bg-white p-6"><h2 className="text-xl font-black">Recordatorios y seguimiento</h2><p className="mt-1 text-sm text-slate-500">Los recordatorios solo se repiten mientras exista una acción pendiente.</p><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{settingFields.map(([key,label,help]) => <label key={key} className="text-sm font-bold text-slate-600"><span className="flex items-center gap-2">{label}<button type="button" title={help} onClick={() => window.alert(help)} className="flex h-5 w-5 items-center justify-center rounded-full border border-blue-500 text-xs font-black text-blue-600">?</button></span><input type="number" min={key === 'maxReminders' || key === 'escalateAfterReminders' || key === 'driverNoShowReportAfterMinutes' || key === 'driverTurnaroundMinutes' ? 0 : 1} value={settings[key]} onChange={(e) => setSettings({ ...settings, [key]: Number(e.target.value) })} className="mt-1 w-full rounded-xl border p-3 text-slate-900" /></label>)}</div><button disabled={busy === "settings"} onClick={() => void save()} className="mt-4 rounded-xl bg-slate-950 px-5 py-3 font-bold text-white">Guardar configuración</button></section>
  </main>;
}
