"use client";
import { useCallback, useEffect, useState } from "react";
import { getPaymentSettings, listPendingPayments, listPendingRefunds, PaymentSettings, reviewPayment, reviewRefund, savePaymentSettings } from "./lib/paymentsApi";
const initial: PaymentSettings = { methods: [{ id: "KEY", label: "Llave", value: "", holder: "", enabled: true }, { id: "NEQUI", label: "Nequi", value: "", holder: "", enabled: true }, { id: "DAVIPLATA", label: "Daviplata", value: "", holder: "", enabled: true }], instructions: "Transfiere el valor exacto y adjunta una captura legible del comprobante." };
export default function PaymentsPage() {
  const [rows, setRows] = useState<any[]>([]), [refunds, setRefunds] = useState<any[]>([]), [settings, setSettings] = useState(initial), [message, setMessage] = useState(""), [busy, setBusy] = useState("");
  const load = useCallback(async () => { try { const [p, r, s] = await Promise.all([listPendingPayments(), listPendingRefunds(), getPaymentSettings()]); setRows(p); setRefunds(r); setSettings(s); } catch (e: any) { setMessage(e.message); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function save() { try { setBusy("settings"); await savePaymentSettings(settings); setMessage("Datos de pago guardados."); } catch (e: any) { setMessage(e.message); } finally { setBusy(""); } }
  async function decide(id: string, decision: "APPROVE" | "REJECT") { const notes = decision === "REJECT" ? window.prompt("Motivo del rechazo:") || undefined : undefined; if (decision === "REJECT" && !notes) return; try { setBusy(id); await reviewPayment(id, decision, notes); await load(); } catch (e: any) { setMessage(e.message); } finally { setBusy(""); } }
  async function decideRefund(id: string, decision: "COMPLETE" | "REJECT") { const notes = window.prompt(decision === "COMPLETE" ? "Referencia, medio o nota de la devolución:" : "Motivo para rechazar la devolución:") || undefined; if (!notes) return; try { setBusy(`refund-${id}`); await reviewRefund(id, decision, notes); await load(); setMessage(decision === "COMPLETE" ? "Devolución registrada y usuario notificado." : "Solicitud rechazada y usuario notificado."); } catch (e: any) { setMessage(e.message); } finally { setBusy(""); } }
  return <main className="space-y-6 p-6"><header><p className="text-sm font-bold text-emerald-600">Ruta KroniX</p><h1 className="text-3xl font-black">Pagos y comprobantes</h1><p className="mt-2 text-sm text-slate-500">Configura los destinos de pago y verifica los comprobantes enviados.</p></header>
    {message ? <div className="rounded-2xl bg-blue-50 p-4 text-sm text-blue-800">{message}</div> : null}
    <section className="space-y-4"><h2 className="text-xl font-black">Devoluciones pendientes <span className="text-red-600">({refunds.length})</span></h2>{refunds.length === 0 ? <div className="rounded-3xl bg-white p-8 text-center text-slate-500">No hay devoluciones pendientes.</div> : refunds.map((row) => <article key={row.id} className="rounded-3xl border border-amber-200 bg-amber-50 p-6"><h3 className="text-lg font-black">{row.user.name}</h3><p className="text-sm text-slate-500">{row.user.phone} · {row.booking.trip.route.originCity.name} → {row.booking.trip.route.destinationCity.name}</p><p className="mt-2 text-sm">Puestos: {row.booking.seats.map((s: any) => s.tripSeat.label).join(", ")}</p><p className="mt-3 text-2xl font-black text-amber-700">{new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 }).format(row.amountCOP)}</p><div className="mt-4 flex gap-2"><button disabled={busy === `refund-${row.id}`} onClick={() => void decideRefund(row.id, "COMPLETE")} className="rounded-xl bg-emerald-600 px-4 py-2 font-bold text-white">Marcar devuelto</button><button disabled={busy === `refund-${row.id}`} onClick={() => void decideRefund(row.id, "REJECT")} className="rounded-xl bg-red-600 px-4 py-2 font-bold text-white">Rechazar devolución</button></div></article>)}</section>
    <section className="rounded-3xl border bg-white p-6"><h2 className="text-xl font-black">Métodos de pago</h2><div className="mt-4 grid gap-4 lg:grid-cols-3">{settings.methods.map((m, index) => <div key={m.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex items-center justify-between"><strong>{m.label}</strong><input type="checkbox" checked={m.enabled} onChange={(e) => setSettings({ ...settings, methods: settings.methods.map((x, i) => i === index ? { ...x, enabled: e.target.checked } : x) })} /></div><label className="mt-3 block text-xs font-bold text-slate-500">Número o llave</label><input className="mt-1 w-full rounded-xl border p-3" value={m.value} onChange={(e) => setSettings({ ...settings, methods: settings.methods.map((x, i) => i === index ? { ...x, value: e.target.value } : x) })} /><label className="mt-3 block text-xs font-bold text-slate-500">Titular</label><input className="mt-1 w-full rounded-xl border p-3" value={m.holder} onChange={(e) => setSettings({ ...settings, methods: settings.methods.map((x, i) => i === index ? { ...x, holder: e.target.value } : x) })} /></div>)}</div><label className="mt-4 block text-xs font-bold text-slate-500">Instrucciones</label><textarea className="mt-1 w-full rounded-xl border p-3" value={settings.instructions} onChange={(e) => setSettings({ ...settings, instructions: e.target.value })} /><button disabled={busy === "settings"} onClick={() => void save()} className="mt-4 rounded-xl bg-slate-950 px-5 py-3 font-bold text-white">Guardar configuración</button></section>
    <section className="space-y-4"><h2 className="text-xl font-black">Comprobantes pendientes <span className="text-red-600">({rows.length})</span></h2>{rows.length === 0 ? <div className="rounded-3xl bg-white p-8 text-center text-slate-500">No hay comprobantes pendientes.</div> : rows.map((row) => <article key={row.id} className="grid gap-5 rounded-3xl border bg-white p-6 lg:grid-cols-[1fr_280px]"><div><h3 className="text-lg font-black">{row.user.name}</h3><p className="text-sm text-slate-500">{row.user.phone} · {row.paymentMethod}</p><p className="mt-3 font-bold">{row.booking.trip.route.originCity.name} → {row.booking.trip.route.destinationCity.name}</p><p className="text-sm text-slate-500">Puestos: {row.booking.seats.map((s: any) => s.tripSeat.label).join(", ")}</p><p className="mt-3 text-2xl font-black text-emerald-700">{new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 }).format(row.amountCOP)}</p><div className="mt-4 flex gap-2"><button disabled={busy === row.id} onClick={() => void decide(row.id, "APPROVE")} className="rounded-xl bg-emerald-600 px-4 py-2 font-bold text-white">Aprobar pago</button><button disabled={busy === row.id} onClick={() => void decide(row.id, "REJECT")} className="rounded-xl bg-red-600 px-4 py-2 font-bold text-white">Rechazar</button></div></div><a href={"/api/ctcc" + row.proofUrl} target="_blank" rel="noreferrer"><img src={"/api/ctcc" + row.proofUrl} alt="Comprobante" className="h-64 w-full rounded-2xl bg-slate-100 object-contain" /></a></article>)}</section>
  </main>;
}
