'use client';
import {useEffect,useState} from 'react';
import {apiFetch} from '@/lib/api';
export default function LunchChannels({config,onSaved}:{config:any;onSaved:()=>Promise<void>}){
 const [draft,setDraft]=useState<any>({}),[locations,setLocations]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[base,setBase]=useState('https://buyer.kronix.co');
 useEffect(()=>{setDraft({...config,publicSlug:config.publicSlug??'la-fortuna-del-sabor'});setLocations((config.locations??[]).map((l:any)=>l.label).join('\n'));},[config]);
 async function save(){setBusy(true);setError('');try{await apiFetch(`/lunch/admin/configs/${config.id}/channels`,{method:'PATCH',body:JSON.stringify({...draft,locations:locations.split('\n').map(s=>s.trim()).filter(Boolean)})});await onSaved();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const url=`${base.replace(/\/$/,'')}/r/${draft.publicSlug}`;
 return <section className="rounded-3xl border bg-white p-4"><h2 className="font-black">Acceso público y pedidos en mesa</h2><label className="mt-3 block text-sm">Nombre del enlace<input className="w-full rounded-xl border p-2" value={draft.publicSlug??''} onChange={e=>setDraft({...draft,publicSlug:e.target.value})}/></label>{['publicLinkEnabled','dineInEnabled'].map(k=><label key={k} className="mt-3 flex gap-2"><input type="checkbox" checked={!!draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.checked})}/>{k==='publicLinkEnabled'?'Activar PUBLIC_LINK':'Activar DINE_IN'}</label>)}<label className="mt-3 block text-sm">Mesas o ubicaciones, una por línea<textarea className="w-full rounded-xl border p-2" value={locations} onChange={e=>setLocations(e.target.value)}/></label>{['KRONIX_APP','PUBLIC_LINK','DINE_IN'].map(k=>{const r=draft.channelCommissions?.[k]??{mode:'PERCENT',value:config.commissionRateBps??800};return <div key={k} className="mt-3"><b className="text-xs">Comisión {k}</b><div className="flex gap-2"><select value={r.mode} onChange={e=>setDraft({...draft,channelCommissions:{...draft.channelCommissions,[k]:{...r,mode:e.target.value}}})}><option value="PERCENT">Porcentaje (100 = 1%)</option><option value="FIXED">Fija en COP</option></select><input className="w-24 rounded border p-2" type="number" min={0} value={r.value} onChange={e=>setDraft({...draft,channelCommissions:{...draft.channelCommissions,[k]:{...r,value:Number(e.target.value)}}})}/></div></div>})}<button disabled={busy} onClick={save} className="mt-4 rounded-xl bg-violet-700 p-3 font-bold text-white">{busy?'Guardando…':'Guardar canales y mesas'}</button>{error?<p role="alert">{error}</p>:null}<label className="mt-4 block text-sm">Dirección web de Buyer<input className="w-full rounded border p-2" value={base} onChange={e=>setBase(e.target.value)}/></label><a href={url} target="_blank" rel="noreferrer" className="mt-3 block break-all text-violet-700">{url}</a><p className="mt-2 text-xs">QR general: {url}?mode=dine-in</p>{(config.locations??[]).map((l:any)=><div key={l.id} className="mt-3 rounded-xl border p-3"><b>{l.label}</b><img alt={`QR ${l.label}`} width={160} height={160} src={`/api/lunch-qr?url=${encodeURIComponent(`${url}?mode=dine-in&mesa=${l.qrToken}`)}`}/><a download={`QR-${l.label}.png`} href={`/api/lunch-qr?url=${encodeURIComponent(`${url}?mode=dine-in&mesa=${l.qrToken}`)}`}>Descargar QR</a><input readOnly aria-label={`Link ${l.label}`} value={`${url}?mode=dine-in&mesa=${l.qrToken}`} className="mt-1 w-full text-xs"/><button className="mt-2 text-xs font-bold" onClick={()=>navigator.clipboard.writeText(`${url}?mode=dine-in&mesa=${l.qrToken}`)}>Copiar enlace de la mesa</button></div>)}</section>;
}
