"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useCtccCity } from "../components/CtccCityContext";
import { apiFetch } from "@/lib/api";

type AnyRow = Record<string, any>;
const MONEY = new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 });
const DAYS = [["MONDAY","Lunes"],["TUESDAY","Martes"],["WEDNESDAY","Miércoles"],["THURSDAY","Jueves"],["FRIDAY","Viernes"],["SATURDAY","Sábado"],["SUNDAY","Domingo"],["HOLIDAY","Festivo"]];

function shortId(v:any){const s=String(v??"");return s?`…${s.slice(-7)}`:"—"}
function statusLabel(v:any){const s=String(v??"").toUpperCase();return ({PENDING_PAYMENT_REVIEW:"Pago por verificar",CONFIRMED:"Confirmado",PREPARING:"Preparando",READY:"Listo",COMPLETED:"Finalizado",REJECTED:"Rechazado"} as any)[s]||s||"—"}
function courierLabel(c:any){if(!c)return "Sin domicilio";const s=String(c.status??"").toUpperCase(),f=String(c.flowStatus??"").toUpperCase();if(s==="DELIVERED"||f==="DELIVERED")return "Entregado";if(s==="EN_ROUTE"||f==="EN_ROUTE")return "En ruta";if(s==="ASSIGNED")return "Domiciliario asignado";if(s==="AVAILABLE")return "Buscando domiciliario";if(s==="CANCELLED"||f==="CANCELLED")return "Cancelado";return f||s||"Activo"}
function badgeClass(v:any){const s=String(v??"").toUpperCase();if(["COMPLETED","DELIVERED"].includes(s))return "bg-emerald-50 text-emerald-700 border-emerald-200";if(["REJECTED","CANCELLED"].includes(s))return "bg-rose-50 text-rose-700 border-rose-200";if(["READY","AVAILABLE","ASSIGNED","EN_ROUTE"].includes(s))return "bg-amber-50 text-amber-700 border-amber-200";return "bg-blue-50 text-blue-700 border-blue-200"}

function isoDate(d:Date){return d.toISOString().slice(0,10)}
function LunchReconciliation({citySlug,configs}:{citySlug?:string;configs:any[]}){
 const now=new Date();
 const [from,setFrom]=useState(()=>`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-01`);
 const [to,setTo]=useState(()=>isoDate(now));
 const [storeId,setStoreId]=useState("");
 const [status,setStatus]=useState("");
 const [report,setReport]=useState<any>({items:[],batches:[],kpis:{}});
 const [selected,setSelected]=useState<string[]>([]);
 const [loading,setLoading]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 const [payOpen,setPayOpen]=useState(false),[method,setMethod]=useState("TRANSFERENCIA"),[reference,setReference]=useState(""),[notes,setNotes]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const p=new URLSearchParams();if(citySlug)p.set("citySlug",citySlug);if(storeId)p.set("storeId",storeId);if(from)p.set("from",from);if(to)p.set("to",to);if(status)p.set("status",status);const d=await apiFetch<any>(`/lunch/admin/reconciliation?${p}`);setReport(d);setSelected(x=>x.filter(id=>d.items?.some((r:any)=>r.id===id&&r.reconciliationStatus!=="PAID")))}catch(e:any){setError(e?.message||"No se pudo cargar la conciliación.")}finally{setLoading(false)}},[citySlug,storeId,from,to,status]);
 useEffect(()=>{load()},[load]);
 const pending=(report.items||[]).filter((r:any)=>r.reconciliationStatus!=="PAID");
 const selectedRows=pending.filter((r:any)=>selected.includes(r.id));
 const selectedCommission=selectedRows.reduce((a:number,r:any)=>a+Number(r.platformCommissionCOP||0),0);
 const allPendingSameStore=useMemo(()=>{if(!pending.length)return false;return new Set(pending.map((x:any)=>x.storeId)).size===1},[pending]);
 function toggle(id:string){setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
 async function markPaid(){if(!selected.length)return;setError("");setOk("");try{const r=await apiFetch<any>("/lunch/admin/reconciliation/mark-paid",{method:"POST",body:JSON.stringify({orderIds:selected,paidMethod:method,paidReference:reference,notes})});setOk(`Conciliación registrada: ${r.ordersCount} pedidos · ${MONEY.format(r.platformCommissionCOP)} para KroniX.`);setSelected([]);setPayOpen(false);setReference("");setNotes("");await load()}catch(e:any){setError(e?.message||"No fue posible registrar el pago.")}}
 const k=report.kpis||{};
 const cards=[["Ventas conciliables",MONEY.format(k.grossSalesCOP||0),`${k.completedOrders||0} pedidos finalizados`,"border-blue-200 bg-blue-50/60"],["Ganancia KroniX",MONEY.format(k.kronixRevenueCOP||0),"Comisión contractual del período","border-violet-200 bg-violet-50/60"],["Pendiente por recibir",MONEY.format(k.pendingCOP||0),`${k.pendingOrders||0} pedidos sin conciliar`,"border-amber-200 bg-amber-50/60"],["Recibido por KroniX",MONEY.format(k.paidCOP||0),`${k.paidOrders||0} pedidos conciliados`,"border-emerald-200 bg-emerald-50/60"]];
 return <div className="space-y-4">
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([a,b,c,d])=><div key={String(a)} className={`rounded-3xl border p-4 shadow-sm ${d}`}><div className="text-xs font-black uppercase tracking-wide text-slate-500">{a}</div><div className="mt-2 text-3xl font-black text-slate-950">{b}</div><div className="mt-2 text-xs text-slate-500">{c}</div></div>)}</div>
  {error?<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 font-bold text-rose-700">{error}</div>:null}{ok?<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 font-bold text-emerald-800">{ok}</div>:null}
  <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-md shadow-slate-200/40">
   <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 bg-gradient-to-r from-white to-slate-50/80 p-5"><div><h3 className="text-lg font-black">Conciliación con restaurantes</h3><p className="text-xs text-slate-500">El restaurante recibe el pago del almuerzo. Aquí controlas la comisión que debe entregar a KroniX.</p></div><button disabled={!selected.length} onClick={()=>setPayOpen(true)} className="rounded-2xl bg-slate-950 px-5 py-3 text-sm font-black text-white disabled:opacity-30">Registrar pago ({selected.length})</button></div>
   <div className="border-b border-slate-200 bg-slate-50/70 p-4"><div className="grid gap-2 md:grid-cols-5"><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="rounded-xl border p-2.5 text-sm"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="rounded-xl border p-2.5 text-sm"/><select value={storeId} onChange={e=>{setStoreId(e.target.value);setSelected([])}} className="rounded-xl border p-2.5 text-sm"><option value="">Todos los restaurantes</option>{configs.map(c=><option key={c.store.id} value={c.store.id}>{c.store.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border p-2.5 text-sm"><option value="">Todos</option><option value="PENDING">Pendientes</option><option value="PAID">Pagados</option></select><button onClick={load} className="rounded-xl border bg-slate-50 p-2.5 text-sm font-black">{loading?"Actualizando…":"Actualizar"}</button></div></div>
   <div className="overflow-x-auto"><table className="w-full border-collapse text-left text-sm"><thead className="border-b border-slate-200 bg-slate-100/80 text-[11px] uppercase tracking-wide text-slate-500"><tr><th className="p-3">Sel.</th><th className="p-3">Pedido</th><th className="p-3">Restaurante</th><th className="p-3">Fecha</th><th className="p-3 text-right">Venta</th><th className="p-3 text-right">% KroniX</th><th className="p-3 text-right">Ganancia KroniX</th><th className="p-3 text-right">Neto restaurante</th><th className="p-3">Estado</th></tr></thead><tbody className="divide-y divide-slate-200 bg-white">{(report.items||[]).map((r:any)=><tr key={r.id} className="transition hover:bg-violet-50/40"><td className="p-3"><input type="checkbox" disabled={r.reconciliationStatus==="PAID"} checked={selected.includes(r.id)} onChange={()=>toggle(r.id)}/></td><td className="p-3 font-mono text-xs">{shortId(r.id)}</td><td className="p-3 font-bold">{r.storeName}</td><td className="p-3 text-xs text-slate-500">{new Date(r.createdAt).toLocaleString("es-CO")}</td><td className="p-3 text-right font-bold">{MONEY.format(r.subtotalCOP||0)}</td><td className="p-3 text-right">{(Number(r.commissionRateBpsSnapshot||0)/100).toFixed(2)}%</td><td className="p-3 text-right font-black text-violet-700">{MONEY.format(r.platformCommissionCOP||0)}</td><td className="p-3 text-right">{MONEY.format(r.restaurantNetCOP||0)}</td><td className="p-3"><span className={`rounded-full border px-2 py-1 text-[10px] font-black ${r.reconciliationStatus==="PAID"?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-amber-200 bg-amber-50 text-amber-700"}`}>{r.reconciliationStatus==="PAID"?"PAGADO":"PENDIENTE"}</span></td></tr>)}</tbody></table></div>
   {!report.items?.length?<div className="p-10 text-center text-sm font-bold text-slate-400">No hay pedidos finalizados para este rango.</div>:null}
   {pending.length?<div className="flex flex-wrap items-center justify-between gap-3 border-t bg-amber-50/50 p-4 text-sm"><div><b>Pendiente total:</b> {MONEY.format(k.pendingCOP||0)} · {pending.length} pedidos</div>{allPendingSameStore?<button onClick={()=>setSelected(pending.map((x:any)=>x.id))} className="font-black text-blue-700">Seleccionar todos los pendientes</button>:<span className="text-xs text-slate-500">Filtra un restaurante para conciliar en lote.</span>}</div>:null}
  </section>
  <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-md shadow-slate-200/40"><div className="border-b border-slate-200 bg-gradient-to-r from-white to-slate-50/80 p-5"><h3 className="font-black text-slate-950">Historial de conciliaciones</h3><p className="mt-1 text-xs text-slate-500">Comprobantes y lotes ya registrados.</p></div>{report.batches?.length?<div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3">{(report.batches||[]).map((b:any)=><div key={b.id} className="rounded-2xl border border-slate-200 bg-slate-50/60 p-4 shadow-sm"><div className="flex justify-between gap-2"><b>{b.storeName}</b><span className="text-[10px] font-black text-emerald-700">PAGADO</span></div><div className="mt-2 text-2xl font-black text-violet-700">{MONEY.format(b.platformCommissionCOP||0)}</div><div className="mt-2 text-xs text-slate-500">{b.ordersCount} pedidos · Ventas {MONEY.format(b.grossSalesCOP||0)}</div><div className="mt-2 text-xs"><b>{b.paidMethod||"—"}</b> · Ref. {b.paidReference||"—"}</div><div className="mt-1 text-xs text-slate-500">{b.paidAt?new Date(b.paidAt).toLocaleString("es-CO"):"—"}</div>{b.notes?<div className="mt-2 rounded-xl border border-slate-200 bg-white p-2 text-xs">{b.notes}</div>:null}</div>)}</div>:<div className="grid min-h-28 place-items-center p-6 text-center"><div><div className="text-sm font-black text-slate-400">Aún no hay conciliaciones registradas</div><div className="mt-1 text-xs text-slate-400">Cuando registres un pago a KroniX, aparecerá aquí con su comprobante y detalle.</div></div></div>}</section>
  {payOpen?<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><h3 className="text-xl font-black">Registrar pago a KroniX</h3><p className="mt-1 text-sm text-slate-500">{selected.length} pedidos · <b className="text-violet-700">{MONEY.format(selectedCommission)}</b> de comisión.</p><div className="mt-5 grid gap-3"><label className="text-sm font-bold">Método<select value={method} onChange={e=>setMethod(e.target.value)} className="mt-1 w-full rounded-xl border p-3"><option>TRANSFERENCIA</option><option>NEQUI</option><option>DAVIPLATA</option><option>EFECTIVO</option><option>OTRO</option></select></label><label className="text-sm font-bold">Referencia / comprobante<input value={reference} onChange={e=>setReference(e.target.value)} className="mt-1 w-full rounded-xl border p-3" placeholder="Número de transferencia o recibo"/></label><label className="text-sm font-bold">Notas<textarea value={notes} onChange={e=>setNotes(e.target.value)} className="mt-1 min-h-24 w-full rounded-xl border p-3" placeholder="Observaciones opcionales"/></label></div><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setPayOpen(false)} className="rounded-xl border px-4 py-2 font-bold">Cancelar</button><button disabled={!reference.trim()} onClick={markPaid} className="rounded-xl bg-emerald-600 px-5 py-2 font-black text-white disabled:opacity-30">Confirmar pago</button></div></div></div>:null}
 </div>
}

function LunchConfigManager({configs,config,setConfig,loadConfigs,message,setMessage}:{configs:any[];config:any;setConfig:(v:any)=>void;loadConfigs:()=>Promise<void>;message:string;setMessage:(v:string)=>void}){
 const [day,setDay]=useState("FRIDAY");
 const [editor,setEditor]=useState<any>(null);
 const [busy,setBusy]=useState(false);
 const menu=config?.menus?.find((m:any)=>m.dayOfWeek===day);
 const label=DAYS.find(([d])=>d===day)?.[1]||day;
 const groups=useMemo(()=>{const m=new Map<string,any[]>();for(const x of menu?.items||[]){const k=String(x.category||"OTROS").toUpperCase();m.set(k,[...(m.get(k)||[]),x])}return [...m.entries()].sort(([a],[b])=>a==="ESPECIALES"?1:b==="ESPECIALES"?-1:Number(a)-Number(b))},[menu]);
 async function reload(msg?:string){await loadConfigs();if(msg)setMessage(msg)}
 async function saveCfg(){if(!config)return;setBusy(true);try{await apiFetch(`/lunch/admin/configs/${config.id}`,{method:"PATCH",body:JSON.stringify(config)});await reload("Configuración guardada.")}finally{setBusy(false)}}
 async function createMenu(){if(!config)return;setBusy(true);try{await apiFetch(`/lunch/admin/configs/${config.id}/menu`,{method:"POST",body:JSON.stringify({dayOfWeek:day,title:`Menú ${label}`,includedText:"",isActive:true})});await reload("Menú creado.")}finally{setBusy(false)}}
 async function patchMenu(body:any){if(!menu)return;setBusy(true);try{await apiFetch(`/lunch/admin/menus/${menu.id}`,{method:"PATCH",body:JSON.stringify(body)});await reload("Menú actualizado.")}finally{setBusy(false)}}
 async function removeMenu(){if(!menu||!confirm(`¿Eliminar completamente el menú ${label}?`))return;setBusy(true);try{await apiFetch(`/lunch/admin/menus/${menu.id}`,{method:"DELETE"});await reload("Menú eliminado.")}finally{setBusy(false)}}
 async function saveItem(){if(!menu||!editor?.name?.trim())return;setBusy(true);try{const path=editor.id?`/lunch/admin/items/${editor.id}`:`/lunch/admin/menus/${menu.id}/items`;await apiFetch(path,{method:editor.id?"PATCH":"POST",body:JSON.stringify(editor)});setEditor(null);await reload(editor.id?"Plato actualizado.":"Plato agregado.")}finally{setBusy(false)}}
 async function toggleItem(x:any){await apiFetch(`/lunch/admin/items/${x.id}`,{method:"PATCH",body:JSON.stringify({isActive:x.isActive===false})});await reload(x.isActive===false?"Plato habilitado.":"Plato pausado.")}
 async function removeItem(x:any){if(!confirm(`¿Eliminar “${x.name}”?`))return;await apiFetch(`/lunch/admin/items/${x.id}`,{method:"DELETE"});await reload("Plato eliminado.")}
 if(!config)return <div className="grid min-h-[480px] place-items-center rounded-3xl border bg-white text-slate-400">Selecciona un restaurante.</div>;
 return <div className="grid min-h-0 gap-4 xl:grid-cols-[350px_minmax(0,1fr)]">
  <aside className="space-y-3">
   <section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><div className="text-[11px] font-black uppercase tracking-widest text-slate-400">Restaurante</div><select value={config.id} onChange={e=>setConfig(configs.find(c=>c.id===e.target.value))} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 p-3 font-black outline-none transition focus:border-slate-400 focus:bg-white">{configs.map(c=><option key={c.id} value={c.id}>{c.store.name}</option>)}</select><div className="mt-3 text-xs font-bold text-slate-500">{config.store?.city?.name} · {config.isActive?"Servicio activo":"Servicio pausado"}</div>
    <label className={`mt-4 flex cursor-pointer items-center justify-between gap-3 rounded-2xl border p-3 ${config.isPublicVisible!==false?"border-emerald-200 bg-emerald-50":"border-slate-200 bg-slate-50"}`}>
     <div><div className="text-xs font-black text-slate-900">Visible al público</div><div className="mt-0.5 text-[10px] font-bold text-slate-500">Control maestro de la tarjeta “Pide un Almuerzo”.</div></div>
     <input type="checkbox" checked={config.isPublicVisible!==false} onChange={e=>setConfig({...config,isPublicVisible:e.target.checked})} className="h-5 w-5 accent-emerald-600"/>
    </label>
   </section>
   <section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div><div className="text-[11px] font-black uppercase tracking-widest text-slate-400">Configuración</div><h3 className="mt-1 font-black">Servicio de almuerzos</h3></div><input type="checkbox" checked={!!config.isActive} onChange={e=>setConfig({...config,isActive:e.target.checked})}/></div><div className="mt-3 space-y-2">{[["Título","serviceTitle","text"],["Subtítulo","serviceSubtitle","text"],["Incluye diariamente","dailyIncludedText","text"],["Apertura","openTime","time"],["Cierre","closeTime","time"],["Medio de pago","paymentMethodLabel","text"],["Cuenta / Llave / Nequi","paymentDestination","text"],["Empaque","packagingUnitCOP","number"]].map(([l,k,t])=><label key={k} className="block text-[10px] font-black uppercase tracking-wide text-slate-400">{l}<input type={t} value={config[k]??""} onChange={e=>setConfig({...config,[k]:t==="number"?Number(e.target.value):e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 bg-slate-50 p-2.5 text-sm font-bold normal-case text-slate-900 outline-none transition focus:border-slate-400 focus:bg-white"/></label>)}<label className="block text-[10px] font-black uppercase tracking-wide text-slate-400">Comisión KroniX (%)<input type="number" step="0.1" value={(config.commissionRateBps??0)/100} onChange={e=>setConfig({...config,commissionRateBps:Number(e.target.value)*100})} className="mt-1 w-full rounded-xl border border-slate-200 bg-slate-50 p-2.5 text-sm font-bold text-slate-900 outline-none transition focus:border-slate-400 focus:bg-white"/></label></div><button onClick={saveCfg} disabled={busy} className="mt-3 w-full rounded-xl bg-emerald-600 px-4 py-3 text-sm font-black text-white">Guardar configuración</button></section>
   <section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><div className="text-[11px] font-black uppercase tracking-widest text-slate-400">Menú semanal</div><div className="mt-3 space-y-2">{DAYS.map(([d,l])=>{const m=config.menus?.find((x:any)=>x.dayOfWeek===d),sel=d===day;return <button key={d} onClick={()=>setDay(d)} className={`flex w-full items-center justify-between rounded-2xl border px-3 py-3 text-left ${sel?"border-slate-950 bg-slate-950 text-white":"border-slate-200 hover:bg-violet-50"}`}><div><div className="font-black">{l}</div><div className={`text-[11px] font-bold ${sel?"text-slate-300":"text-slate-500"}`}>{m?`${m.items?.length||0} platos${m.isActive===false?" · pausado":""}`:"Pendiente de configurar"}</div></div><span>›</span></button>})}</div></section>
  </aside>
  <section className="min-w-0 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="sticky top-0 z-10 border-b bg-white/95 p-5 backdrop-blur"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[11px] font-black uppercase tracking-widest text-violet-600">Menú seleccionado</div><h2 className="mt-1 text-2xl font-black">{menu?.title||`Menú ${label}`}</h2><p className="text-sm font-bold text-slate-500">{menu?.includedText||"Sin descripción del día"}</p></div><div className="flex flex-wrap gap-2">{!menu?<button onClick={createMenu} className="rounded-xl bg-violet-600 px-4 py-2 text-sm font-black text-white">+ Cargar menú</button>:<><button onClick={()=>patchMenu({isActive:menu.isActive===false})} className="rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-xs font-black text-amber-700">{menu.isActive===false?"Habilitar menú":"Pausar menú"}</button><button onClick={()=>setEditor({name:"",category:"15000",priceCOP:15000,description:"",sortOrder:(menu.items?.length||0)*10+10})} className="rounded-xl bg-emerald-600 px-4 py-2 text-xs font-black text-white">+ Agregar plato</button><button onClick={removeMenu} className="rounded-xl bg-rose-50 px-3 py-2 text-xs font-black text-rose-700">Eliminar menú</button></>}</div></div>{message?<div className="mt-3 rounded-xl bg-emerald-50 px-3 py-2 text-xs font-black text-emerald-700">{message}</div>:null}</div>
   <div className="max-h-[calc(100dvh-250px)] overflow-y-auto p-5 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{!menu?<div className="grid min-h-[420px] place-items-center rounded-2xl border border-dashed bg-slate-50 text-center text-slate-400"><div><div className="text-5xl">🍽️</div><div className="mt-3 font-black">{label} aún no tiene menú</div></div></div>:<div className="space-y-4">{groups.map(([cat,items])=><section key={cat} className="rounded-3xl bg-slate-50/80 p-3 shadow-sm ring-1 ring-slate-200/70"><div className="flex items-center justify-between px-2 pb-3 pt-1"><div><b className="text-base font-black text-violet-700">{cat==="ESPECIALES"?"Especiales":MONEY.format(Number(cat)||0)}</b><div className="mt-0.5 text-[11px] font-semibold text-slate-400">Categoría del menú</div></div><span className="rounded-full bg-white px-3 py-1 text-xs font-bold text-slate-500 shadow-sm">{items.length} platos</span></div><div className="grid gap-2 lg:grid-cols-2">{items.map((x:any)=><article key={x.id} className={`flex min-h-[82px] items-center justify-between gap-3 rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200/60 transition hover:shadow-md ${x.isActive===false?"opacity-55":""}`}><div className="min-w-0"><div className="font-black text-slate-950">{x.name}</div><div className="mt-1 text-xs font-bold text-slate-500">{MONEY.format(x.priceCOP)} · <span className={x.isActive===false?"text-amber-700":"text-emerald-700"}>{x.isActive===false?"Sin stock":"Disponible"}</span></div></div><div className="flex shrink-0 gap-1.5"><button onClick={()=>setEditor({...x})} className="rounded-lg bg-slate-100 px-2.5 py-1.5 text-xs font-black text-slate-700 transition hover:bg-slate-200">Editar</button><button onClick={()=>toggleItem(x)} className="rounded-lg bg-amber-50 px-2.5 py-1.5 text-xs font-black text-amber-700 transition hover:bg-amber-100">{x.isActive===false?"Habilitar":"Pausar"}</button><button onClick={()=>removeItem(x)} className="rounded-lg bg-rose-50 px-2.5 py-1.5 text-xs font-black text-rose-700 transition hover:bg-rose-100">×</button></div></article>)}</div></section>)}</div>}</div>
  </section>
  {editor?<div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/45 p-4 backdrop-blur-sm"><div className="w-full max-w-xl rounded-3xl bg-white p-5 shadow-2xl"><div className="flex justify-between"><div><div className="text-xs font-black uppercase tracking-widest text-violet-600">{editor.id?"Editar plato":"Nuevo plato"}</div><h3 className="mt-1 text-xl font-black">Menú {label}</h3></div><button onClick={()=>setEditor(null)} className="rounded-xl bg-slate-100 px-3 font-black">×</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><input placeholder="Nombre" value={editor.name||""} onChange={e=>setEditor({...editor,name:e.target.value})} className="rounded-xl border p-3 sm:col-span-2"/><input placeholder="Categoría: 15000 o ESPECIALES" value={editor.category||""} onChange={e=>setEditor({...editor,category:e.target.value.toUpperCase()})} className="rounded-xl border p-3"/><input type="number" placeholder="Precio" value={editor.priceCOP||0} onChange={e=>setEditor({...editor,priceCOP:Number(e.target.value)})} className="rounded-xl border p-3"/><textarea placeholder="Descripción" value={editor.description||""} onChange={e=>setEditor({...editor,description:e.target.value})} className="rounded-xl border p-3 sm:col-span-2"/></div><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setEditor(null)} className="rounded-xl border px-4 py-2 font-black">Cancelar</button><button onClick={saveItem} disabled={busy} className="rounded-xl bg-violet-600 px-5 py-2 font-black text-white">Guardar plato</button></div></div></div>:null}
 </div>
}

export default function LunchAdmin(){
 const {citySlug,isGlobal}=useCtccCity();
 const [tab,setTab]=useState<"ORDERS"|"RECON"|"CONFIG">("ORDERS");
 const [data,setData]=useState<any>({items:[],kpis:{}}),[configs,setConfigs]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[config,setConfig]=useState<any>(null);
 const [loading,setLoading]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [status,setStatus]=useState(""),[fulfillment,setFulfillment]=useState(""),[storeId,setStoreId]=useState(""),[search,setSearch]=useState("");

 const loadConfigs=useCallback(async()=>{const q=citySlug?`?citySlug=${encodeURIComponent(citySlug)}`:"";const rows=await apiFetch<any[]>(`/lunch/admin/configs${q}`);setConfigs(rows);setConfig((prev:any)=>rows.find((r:any)=>r.id===prev?.id)??rows[0]??null);},[citySlug]);
 const loadOrders=useCallback(async()=>{setLoading(true);setError("");try{const p=new URLSearchParams();if(citySlug)p.set("citySlug",citySlug);if(status)p.set("status",status);if(fulfillment)p.set("fulfillment",fulfillment);if(storeId)p.set("storeId",storeId);if(search.trim())p.set("search",search.trim());const d=await apiFetch<any>(`/lunch/admin/orders?${p.toString()}`);setData(d);if(selected){const fresh=d.items?.find((x:any)=>x.id===selected.id);if(fresh)setSelected(fresh)}}catch(e:any){setError(e?.message||"No se pudieron cargar los pedidos.")}finally{setLoading(false)}},[citySlug,status,fulfillment,storeId,search,selected?.id]);
 useEffect(()=>{loadConfigs().catch((e:any)=>setError(e.message));},[citySlug]);
 useEffect(()=>{if(tab!=="ORDERS")return;loadOrders();const t=setInterval(loadOrders,8000);return()=>clearInterval(t)},[tab,citySlug,status,fulfillment,storeId]);

 const k=data?.kpis||{};
 const cards=[
  ["Pedidos hoy",k.today??0,"Pedidos creados hoy","border-blue-200 bg-blue-50/60 text-blue-700"],
  ["Pago pendiente",k.pending??0,"Pendientes de verificación","border-amber-200 bg-amber-50/60 text-amber-700"],
  ["Preparando",k.preparing??0,"Confirmados o en cocina","border-cyan-200 bg-cyan-50/60 text-cyan-700"],
  ["Listos",k.ready??0,"Listos para recoger / despachar","border-violet-200 bg-violet-50/60 text-violet-700"],
  ["En domicilio",k.deliveryActive??0,"Con Domi-Almuerzo asociado","border-sky-200 bg-sky-50/60 text-sky-700"],
  ["Finalizados",k.completed??0,"Pedidos completados en la vista","border-emerald-200 bg-emerald-50/60 text-emerald-700"],
  ["Ventas hoy",MONEY.format(k.todaySalesCOP??0),"Valor de almuerzos creados hoy","border-fuchsia-200 bg-fuchsia-50/50 text-fuchsia-700"],
 ];
 async function saveConfig(){if(!config)return;setMessage("");await apiFetch(`/lunch/admin/configs/${config.id}`,{method:"PATCH",body:JSON.stringify(config)});setMessage("Configuración guardada.");await loadConfigs()}
 async function addMenu(day:string,label:string){if(!config)return;await apiFetch(`/lunch/admin/configs/${config.id}/menu`,{method:"POST",body:JSON.stringify({dayOfWeek:day,title:`Menú ${label}`})});await loadConfigs()}
 async function addItem(menuId:string){const name=prompt("Nombre del plato");if(!name)return;const category=prompt("Categoría", "15000")||"15000";const priceCOP=Number(prompt("Precio",category)||0);await apiFetch(`/lunch/admin/menus/${menuId}/items`,{method:"POST",body:JSON.stringify({name,category,priceCOP})});await loadConfigs()}

 return <main className="min-h-full space-y-5 bg-slate-50/70 p-4 md:p-6">
  <section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm">
   <div className="flex flex-wrap items-center justify-between gap-3">
    <div>
     <h2 className="text-2xl font-black tracking-tight text-slate-950">Control de Almuerzos</h2>
     <p className="mt-1 text-sm text-slate-500">Supervisión operativa del pedido, restaurante y logística Domi-Almuerzo.</p>
    </div>
    <div className="flex rounded-2xl border border-slate-200 bg-slate-50 p-1">
     <button onClick={()=>setTab("ORDERS")} className={`rounded-xl px-5 py-2 text-sm font-black transition ${tab==="ORDERS"?"bg-slate-950 text-white shadow-sm":"text-slate-600 hover:bg-white"}`}>Pedidos</button>
     <button onClick={()=>setTab("RECON")} className={`rounded-xl px-5 py-2 text-sm font-black transition ${tab==="RECON"?"bg-slate-950 text-white shadow-sm":"text-slate-600 hover:bg-white"}`}>Conciliación</button>
     <button onClick={()=>setTab("CONFIG")} className={`rounded-xl px-5 py-2 text-sm font-black transition ${tab==="CONFIG"?"bg-slate-950 text-white shadow-sm":"text-slate-600 hover:bg-white"}`}>Configuración</button>
    </div>
   </div>
  </section>
  {error?<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 font-bold text-rose-700">{error}</div>:null}

  {tab==="ORDERS"?<>
   <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([a,b,h,c])=><div key={String(a)} className={`rounded-3xl border p-4 shadow-sm ${c}`}><div className="text-xs font-semibold uppercase tracking-wide opacity-70">{a}</div><div className="mt-2 text-3xl font-black tracking-tight text-slate-950">{b}</div><div className="mt-2 text-xs text-slate-500">{h}</div></div>)}</div>
   <div className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]">
    <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
     <div className="border-b border-slate-200 px-4 py-4"><div className="font-black text-slate-950">Listado de pedidos de almuerzo</div><div className="mt-1 text-xs text-slate-500">Filtra y selecciona un pedido para revisar su trazabilidad completa.</div></div>
     <div className="p-4"><div className="rounded-2xl border border-slate-200 bg-slate-50/80 p-3 shadow-sm"><div className="grid gap-2 md:grid-cols-4"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&loadOrders()} placeholder="ID, cliente, teléfono…" className="rounded-xl border p-2.5 text-sm"/><select value={storeId} onChange={e=>setStoreId(e.target.value)} className="rounded-xl border p-2.5 text-sm"><option value="">Todos los restaurantes</option>{configs.map(c=><option key={c.store.id} value={c.store.id}>{c.store.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border p-2.5 text-sm"><option value="">Todos los estados</option><option value="PENDING_PAYMENT_REVIEW">Pago por verificar</option><option value="CONFIRMED">Confirmado</option><option value="PREPARING">Preparando</option><option value="READY">Listo</option><option value="COMPLETED">Finalizado</option><option value="REJECTED">Rechazado</option></select><select value={fulfillment} onChange={e=>setFulfillment(e.target.value)} className="rounded-xl border p-2.5 text-sm"><option value="">Entrega / Recogida</option><option value="DELIVERY">A domicilio</option><option value="PICKUP">Recoge cliente</option></select></div>
     </div><div className="mt-3 flex items-center justify-between border-t border-slate-200 pt-3 text-xs text-slate-500"><span>{isGlobal?"Vista global":`Ciudad: ${citySlug}`} · {data.items?.length??0} pedidos</span><button onClick={loadOrders} className="font-black text-blue-700">{loading?"Actualizando…":"Actualizar"}</button></div>
     <div className="mt-4 max-h-[62vh] space-y-3 overflow-auto pr-1 [scrollbar-width:thin]">{(data.items||[]).map((r:any)=><button key={r.id} onClick={()=>setSelected(r)} className={`w-full rounded-2xl border p-4 text-left transition ${selected?.id===r.id?"border-slate-900 bg-slate-50":"border-slate-200 hover:bg-slate-50"}`}><div className="flex items-start justify-between gap-3"><div><div className="font-black">{r.customer?.name||"Cliente"} · {shortId(r.id)}</div><div className="mt-1 text-xs text-slate-500">{r.store?.name} · {new Date(r.createdAt).toLocaleString("es-CO")}</div></div><div className="text-right"><div className="font-black">{MONEY.format(r.subtotalCOP||0)}</div><span className={`mt-1 inline-block rounded-full border px-2 py-1 text-[10px] font-black ${badgeClass(r.status)}`}>{statusLabel(r.status)}</span></div></div><div className="mt-3 flex flex-wrap gap-2 text-[11px] font-bold"><span className="rounded-full bg-violet-50 px-2 py-1 text-violet-700">{r.fulfillment==="PICKUP"?"Recoge cliente":"A domicilio"}</span>{r.courierOrderId?<span className="rounded-full bg-amber-50 px-2 py-1 text-amber-700">Domi-Almuerzo {shortId(r.courierOrderId)} · {courierLabel(r.courier)}</span>:null}</div></button>)}</div></div>
    </section>
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">{!selected?<div className="grid min-h-[420px] place-items-center text-center text-slate-400"><div><div className="text-5xl">🍽️</div><p className="mt-3 font-bold">Selecciona un pedido para supervisarlo.</p></div></div>:<div><div className="flex items-start justify-between"><div><div className="text-xs font-black uppercase tracking-widest text-violet-600">Pedido de almuerzo</div><h2 className="text-2xl font-black">{shortId(selected.id)}</h2></div><span className={`rounded-full border px-3 py-1 text-xs font-black ${badgeClass(selected.status)}`}>{statusLabel(selected.status)}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["Cliente",selected.customer?.name],["Teléfono",selected.customer?.phone],["Restaurante",selected.store?.name],["Modalidad",selected.fulfillment==="PICKUP"?"Recoge en restaurante":"A domicilio"],["Pago",selected.paymentMethod],["Referencia",selected.paymentReference],["Dirección",selected.deliveryAddress||"—"],["Total",MONEY.format(selected.subtotalCOP||0)]].map(([a,b])=><div key={String(a)} className="rounded-2xl bg-slate-50 p-3"><div className="text-[10px] font-black uppercase text-slate-400">{a}</div><div className="mt-1 text-sm font-bold">{b||"—"}</div></div>)}</div><div className="mt-5"><h3 className="font-black">Detalle</h3><div className="mt-2 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="divide-y divide-slate-200 px-4">{(selected.itemsSnapshot||[]).map((x:any,i:number)=><div key={i} className="flex justify-between gap-3 py-3 text-sm"><span className="font-semibold text-slate-700">{x.qty} × {x.name}</span><b className="text-slate-950">{MONEY.format((x.totalCOP??x.priceCOP*x.qty)||0)}</b></div>)}</div></div></div>{selected.fulfillment==="DELIVERY"?<div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="text-xs font-black uppercase tracking-widest text-amber-700">Logística Domi-Almuerzo</div>{selected.courierOrderId?<><div className="mt-2 font-black">{shortId(selected.courierOrderId)} · {courierLabel(selected.courier)}</div><div className="mt-1 text-sm">Domiciliario: <b>{selected.courier?.driver?.name||"Aún sin asignar"}</b></div><div className="text-sm">Teléfono: <b>{selected.courier?.driver?.phone||"—"}</b></div></>:<div className="mt-2 text-sm font-bold">Todavía no se ha creado el domicilio. Se genera cuando el restaurante marca el almuerzo como listo.</div>}</div>:<div className="mt-5 rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800">Recogida en restaurante: este pedido no utiliza domiciliario.</div>}</div>}</section>
   </div>
  </>:tab==="RECON"?<LunchReconciliation citySlug={citySlug} configs={configs}/>:<LunchConfigManager configs={configs} config={config} setConfig={setConfig} loadConfigs={loadConfigs} message={message} setMessage={setMessage}/>}
 </main>
}
