"use client";

import { useCallback, useEffect, useState } from "react";
import { listNotificationCampaigns, listNotificationTemplates, NotificationCampaign, NotificationTemplate, sendNotification, updateNotificationTemplate } from "./lib/notificationsApi";

const audienceLabel: Record<string, string> = { ALL: "Todos", PASSENGERS: "Compañeros de ruta", PASSENGER: "Compañero", DRIVERS: "Conductores", DRIVER: "Conductor", USER: "Un usuario", CTCC: "CTCC" };

export default function RutaNotificationsPage() {
  const [templates, setTemplates] = useState<NotificationTemplate[]>([]);
  const [campaigns, setCampaigns] = useState<NotificationCampaign[]>([]);
  const [draft, setDraft] = useState({ title: "", body: "", audience: "ALL" as "ALL" | "PASSENGERS" | "DRIVERS" | "USER", targetPhone: "", actionUrl: "", pushEnabled: true, soundEnabled: true });
  const [editing, setEditing] = useState<NotificationTemplate | null>(null);
  const [busy, setBusy] = useState(""), [message, setMessage] = useState("");
  const load = useCallback(async () => { try { const [t, c] = await Promise.all([listNotificationTemplates(), listNotificationCampaigns()]); setTemplates(t); setCampaigns(c); } catch (e: any) { setMessage(e.message); } }, []);
  useEffect(() => { void load(); }, [load]);

  async function send() {
    if (!draft.title.trim() || !draft.body.trim()) return setMessage("Escribe el título y el mensaje.");
    if (draft.audience === "USER" && !draft.targetPhone.trim()) return setMessage("Escribe el celular del destinatario.");
    try { setBusy("send"); const result = await sendNotification({ ...draft, targetPhone: draft.targetPhone || undefined, actionUrl: draft.actionUrl || undefined }); setMessage(`Notificación enviada a ${result.recipientCount} usuario(s).`); setDraft({ ...draft, title: "", body: "", targetPhone: "", actionUrl: "" }); await load(); } catch (e: any) { setMessage(e.message); } finally { setBusy(""); }
  }

  async function saveTemplate() {
    if (!editing) return;
    try { setBusy(editing.id); await updateNotificationTemplate(editing.id, { name: editing.name, title: editing.title, body: editing.body, actionUrl: editing.actionUrl, priority: editing.priority, isActive: editing.isActive, pushEnabled: editing.pushEnabled, soundEnabled: editing.soundEnabled, recurringEnabled: editing.recurringEnabled }); setEditing(null); setMessage("Plantilla actualizada."); await load(); } catch (e: any) { setMessage(e.message); } finally { setBusy(""); }
  }

  return <main className="space-y-6 p-6">
    <header><p className="text-sm font-bold text-emerald-600">Ruta KroniX</p><h1 className="text-3xl font-black text-slate-950">Centro de notificaciones</h1><p className="mt-2 text-sm text-slate-500">Controla los avisos automáticos y envía comunicaciones manuales a los usuarios.</p></header>
    {message ? <div className="rounded-2xl bg-blue-50 p-4 text-sm font-semibold text-blue-800">{message}</div> : null}

    <section className="rounded-3xl border bg-white p-6"><h2 className="text-xl font-black">Crear notificación</h2><div className="mt-4 grid gap-4 lg:grid-cols-2"><label className="text-sm font-bold text-slate-600">Título<input value={draft.title} onChange={(e) => setDraft({ ...draft, title: e.target.value })} className="mt-1 w-full rounded-xl border p-3 text-slate-900" maxLength={120} /></label><label className="text-sm font-bold text-slate-600">Destinatarios<select value={draft.audience} onChange={(e) => setDraft({ ...draft, audience: e.target.value as typeof draft.audience })} className="mt-1 w-full rounded-xl border p-3 text-slate-900"><option value="ALL">Todos los usuarios Ruta KroniX</option><option value="PASSENGERS">Compañeros de ruta</option><option value="DRIVERS">Conductores aprobados</option><option value="USER">Un usuario por celular</option></select></label>{draft.audience === "USER" ? <label className="text-sm font-bold text-slate-600">Celular<input value={draft.targetPhone} onChange={(e) => setDraft({ ...draft, targetPhone: e.target.value })} className="mt-1 w-full rounded-xl border p-3 text-slate-900" placeholder="3110000000" /></label> : null}<label className="text-sm font-bold text-slate-600">Destino al tocar (opcional)<input value={draft.actionUrl} onChange={(e) => setDraft({ ...draft, actionUrl: e.target.value })} className="mt-1 w-full rounded-xl border p-3 text-slate-900" placeholder="/(tabs)/trips" /></label><label className="text-sm font-bold text-slate-600 lg:col-span-2">Mensaje<textarea value={draft.body} onChange={(e) => setDraft({ ...draft, body: e.target.value })} className="mt-1 min-h-28 w-full rounded-xl border p-3 text-slate-900" maxLength={500} /></label></div><div className="mt-4 flex flex-wrap items-center gap-5"><Toggle label="Push" checked={draft.pushEnabled} onChange={(value) => setDraft({ ...draft, pushEnabled: value })} /><Toggle label="Sonido" checked={draft.soundEnabled} onChange={(value) => setDraft({ ...draft, soundEnabled: value })} /><button disabled={busy === "send"} onClick={() => void send()} className="ml-auto rounded-xl bg-slate-950 px-5 py-3 font-black text-white disabled:opacity-50">Enviar ahora</button></div></section>

    <section><h2 className="text-xl font-black">Notificaciones automáticas</h2><p className="mt-1 text-sm text-slate-500">Puedes editar el texto, apagar Push o sonido y suspender cada evento sin modificar código.</p><div className="mt-4 grid gap-4 xl:grid-cols-2">{templates.map((item) => <article key={item.id} className="rounded-3xl border bg-white p-5"><div className="flex items-start justify-between gap-3"><div><span className="text-xs font-black text-emerald-600">{audienceLabel[item.audience] || item.audience}</span><h3 className="font-black text-slate-950">{item.name}</h3><p className="mt-1 text-sm font-semibold text-slate-700">{item.title}</p><p className="mt-1 text-sm text-slate-500">{item.body}</p></div><span className={"rounded-full px-3 py-1 text-xs font-black " + (item.isActive ? "bg-emerald-100 text-emerald-700" : "bg-slate-200 text-slate-600")}>{item.isActive ? "Activa" : "Suspendida"}</span></div><div className="mt-4 flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-lg bg-blue-50 px-2 py-1 text-blue-700">Push: {item.pushEnabled ? "Sí" : "No"}</span><span className="rounded-lg bg-violet-50 px-2 py-1 text-violet-700">Sonido: {item.soundEnabled ? "Sí" : "No"}</span><span className="rounded-lg bg-amber-50 px-2 py-1 text-amber-700">Recurrente: {item.recurringEnabled ? "Sí" : "No"}</span></div><button onClick={() => setEditing({ ...item })} className="mt-4 rounded-xl border px-4 py-2 text-sm font-black text-slate-700">Editar configuración</button></article>)}</div></section>

    <section className="rounded-3xl border bg-white p-6"><h2 className="text-xl font-black">Historial de envíos manuales</h2><div className="mt-4 space-y-3">{campaigns.length ? campaigns.map((item) => <div key={item.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex flex-wrap justify-between gap-2"><strong>{item.title}</strong><span className="text-xs font-bold text-slate-500">{new Date(item.sentAt).toLocaleString("es-CO")}</span></div><p className="mt-1 text-sm text-slate-600">{item.body}</p><p className="mt-2 text-xs font-bold text-emerald-700">{audienceLabel[item.audience] || item.audience} · {item.recipientCount} destinatario(s)</p></div>) : <p className="text-sm text-slate-500">Todavía no hay envíos manuales.</p>}</div></section>

    {editing ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6"><div className="flex justify-between gap-4"><h2 className="text-xl font-black">Editar notificación automática</h2><button onClick={() => setEditing(null)} className="text-2xl">×</button></div><div className="mt-5 grid gap-4"><Field label="Nombre" value={editing.name} onChange={(value) => setEditing({ ...editing, name: value })} /><Field label="Título" value={editing.title} onChange={(value) => setEditing({ ...editing, title: value })} /><label className="text-sm font-bold text-slate-600">Mensaje<textarea value={editing.body} onChange={(e) => setEditing({ ...editing, body: e.target.value })} className="mt-1 min-h-28 w-full rounded-xl border p-3 text-slate-900" /></label><Field label="Destino al tocar" value={editing.actionUrl || ""} onChange={(value) => setEditing({ ...editing, actionUrl: value })} /><label className="text-sm font-bold text-slate-600">Prioridad<select value={editing.priority} onChange={(e) => setEditing({ ...editing, priority: e.target.value as NotificationTemplate["priority"] })} className="mt-1 w-full rounded-xl border p-3"><option value="NORMAL">Normal</option><option value="HIGH">Alta</option><option value="CRITICAL">Crítica</option></select></label><div className="flex flex-wrap gap-5"><Toggle label="Activa" checked={editing.isActive} onChange={(value) => setEditing({ ...editing, isActive: value })} /><Toggle label="Push" checked={editing.pushEnabled} onChange={(value) => setEditing({ ...editing, pushEnabled: value })} /><Toggle label="Sonido" checked={editing.soundEnabled} onChange={(value) => setEditing({ ...editing, soundEnabled: value })} /><Toggle label="Recordatorios" checked={editing.recurringEnabled} onChange={(value) => setEditing({ ...editing, recurringEnabled: value })} /></div></div><div className="mt-6 flex justify-end gap-3"><button onClick={() => setEditing(null)} className="rounded-xl border px-4 py-2 font-bold">Cancelar</button><button disabled={busy === editing.id} onClick={() => void saveTemplate()} className="rounded-xl bg-emerald-600 px-5 py-2 font-black text-white">Guardar cambios</button></div></div></div> : null}
  </main>;
}

function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex items-center gap-2 text-sm font-bold text-slate-700"><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} className="h-4 w-4" />{label}</label>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-sm font-bold text-slate-600">{label}<input value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 w-full rounded-xl border p-3 text-slate-900" /></label>; }
